# GitHub Actions Workflow to handle the release process based on the pre-release prepared with the Build workflow.
# Will delete the latest pre-release and build a new release with version incrementation.

name: PromotePreRelease
on: [ workflow_dispatch ]

jobs:
  prepare:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      baseVersion: ${{ steps.baseProperties.outputs.baseVersion }}
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
      releaseSha: ${{ steps.sha.outputs.releaseSha }}
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/wrapper-validation-action@v1.1.0

      # Export pre-release (snapshot) version
      - name: Export base version properties
        id: baseProperties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"

          echo "$VERSION"
          echo "baseVersion=$VERSION" >> $GITHUB_OUTPUT

      # Set release version
      - name: Trim dev suffix
        id: setReleaseVersions
        shell: bash
        run: ./gradlew setversions --suffix=false

      # Export release version, name and changelog
      - name: Export new commit properties
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          CHANGELOG="$(./gradlew getChangelog --unreleased --no-header --console=plain -q)"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT

      # Update Unreleased section with the current version in the changelog
      - name: Patch Changelog
        run: ./gradlew patchChangelog

      # Commit patched changelog and release version
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Release ${{ steps.properties.outputs.version }}"
          skip_fetch: true

      # Get commit sha
      - shell: bash
        id: sha
        run: |
          RELEASE_SHA="$(git rev-parse HEAD)"
          echo "releaseSha=$RELEASE_SHA" >> $GITHUB_OUTPUT

  release:
    name: Release
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare.outputs.releaseSha }}

      # Create GitHub release
      - name: Create Release
        id: createRelease
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.prepare.outputs.version }}
          tag: ${{ needs.prepare.outputs.version }}
          commit: ${{ needs.prepare.outputs.releaseSha }}
          body: ${{ needs.prepare.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Publish Gradle plugin
      - name: Publish plugin
        id: publish
        shell: bash
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

      # Delete promoted pre release
      - name: Delete previous release
        id: deletePreviousRelease
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare.outputs.baseVersion }}

  finalize:
    name: Prepare next development
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 15
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.ref }}

      # Set next dev version
      - name: Increment version for dev
        id: setDevVersions
        shell: bash
        run: ./gradlew setversions --suffix=true --increment=technical

      # Commit dev version
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "To dev version"
